services:
  - type: web
    name: fiap-tech-challenge-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install poetry
      poetry install --no-dev
    startCommand: poetry run uvicorn fiap_tech_challenge_5mlet.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: src
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXP_DELTA_SECONDS
        value: 3600
      - key: TEST_USERNAME
        value: ${TEST_USERNAME}
      - key: TEST_PASSWORD
        value: ${TEST_PASSWORD}